### ISSUE TITLE
images

### ISSUE THREAD

**Issue by AdarshBelavatagi** [AdarshBelavatagi/CEER#1]
![objective tree - page 1](https://user-images.githubusercontent.com/16568687/28256149-12a4b59e-6add-11e7-8c1e-0aa9da2c3d45.png)

**Comment by AdarshBelavatagi** [comment]
![objective tree - page 1](https://user-images.githubusercontent.com/16568687/28256194-82e839e8-6add-11e7-9b97-c1f3b0794efb.jpeg)

**Comment by AdarshBelavatagi** [comment]
![img_20170717_120924](https://user-images.githubusercontent.com/16568687/28257753-b1719b58-6aea-11e7-9d31-7fd9e713b6c5.jpg)
![img_20170717_120954](https://user-images.githubusercontent.com/16568687/28257787-fa8f92b8-6aea-11e7-8606-805cc72ffdea.jpg)

**Comment by AdarshBelavatagi** [comment]
![tomsplanner](https://user-images.githubusercontent.com/16568687/28258238-c25571a8-6aed-11e7-86ce-66d6383723e3.png)

**Comment by AdarshBelavatagi** [comment]
![img_20170717_131204](https://user-images.githubusercontent.com/16568687/28262544-f702f426-6b00-11e7-8d7f-30417be20962.jpg)

**Comment by madhuasundi** [comment]
![final circuit_schem](https://user-images.githubusercontent.com/16751510/28311634-e897e004-6bcd-11e7-9465-51f21a5b7a5b.jpg)
